blank_issues_enabled: false
contact_links:
    - name: General discussion
      url: https://github.com/Plants-vs-Zombies-MODDED/discussions
      about: Use discussions for chat, memes, and non-bug/non-feature topics.
